version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
pre_build:
    commands:
      - echo Just listing basic information about the environment
      - which mvn
      - mvn -version
      - pwd
