 version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk8
     steps:
       - checkout
       - run: echo "A first hello"
       - run: echo Just listing basic information about the environment
      - run: which mvn
      -run: mvn -version
      - run: pwd
